version: '3.8'

services:
  # Приложение Spring Boot
  app:
    image: cliniktour-app-prod
    build: .
    container_name: cliniktour-app-prod
    ports:
      - "2817:2817"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-cvnvl17gi27c73bpk5qg-a.oregon-postgres.render.com:5432/clinictourtest
      - SPRING_DATASOURCE_USERNAME=clinictourtest_user
      - SPRING_DATASOURCE_PASSWORD=TlAU13dexHmm9k887ps2Mik88ECwePWc
      - IMGUR_CLIENT_ID=${IMGUR_CLIENT_ID}
      - IMGUR_ACCESS_TOKEN=${IMGUR_ACCESS_TOKEN}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - app-data:/app/data
      - app-logs:/app/logs
    restart: always

volumes:
  app-data:
    name: cliniktour-app-prod-data
  app-logs:
    name: cliniktour-app-prod-logs