version: '3.8'

services:
  # База данных PostgreSQL
  postgres:
    image: postgres:14-alpine
    container_name: cliniktour-postgres
    environment:
      POSTGRES_DB: ClinikTourTest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19111993
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Приложение Spring Boot
  app:
    image: cliniktour-app
    build: .
    container_name: cliniktour-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "2817:2817"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ClinikTourTest
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=19111993
      - IMGUR_CLIENT_ID=9a20435fe3d92ba
      - IMGUR_ACCESS_TOKEN=1d2936032980eea70b010f5e8ad63326d19649a3
      - ADMIN_USERNAME=q
      - ADMIN_PASSWORD=q
    volumes:
      - app-data:/app/data
      - app-logs:/app/logs
    restart: unless-stopped

volumes:
  postgres-data:
  app-data:
  app-logs: